/**
 * issue-builder — Format and create GitHub issues for extension findings
 *
 * Adapter layer: calls `gh` CLI via exec function.
 */

import type { Finding } from "./extension-scanner.ts";

/** Exec function signature matching pi.exec */
export type ExecFn = (
	command: string,
	args: string[],
	options?: { cwd?: string; timeout?: number },
) => Promise<{ stdout: string; stderr: string; code: number; killed: boolean }>;

/**
 * Build issue title following spec:
 * [ext-audit] <extension-name>: <N> API changes — pi <version>
 */
export function buildIssueTitle(
	extensionName: string,
	changeCount: number,
	version: string,
): string {
	const changeWord = changeCount === 1 ? "change" : "changes";
	return `[ext-audit] ${extensionName}: ${changeCount} API ${changeWord} — pi ${version}`;
}

/**
 * Build issue body with file paths, API names, changelog ref.
 */
export function buildIssueBody(
	extensionName: string,
	findings: Finding[],
	version: string,
): string {
	const lines: string[] = [];
	lines.push(`# Extension Audit: ${extensionName}`);
	lines.push(``);
	lines.push(
		`This issue tracks API changes in **pi ${version}** that affect the \`${extensionName}\` extension.`,
	);
	lines.push(``);
	lines.push(`## Changelog Reference`);
	lines.push(``);
	lines.push(`Pi version \`${version}\` contains changes that impact this extension.`);
	lines.push(``);

	// Split findings into breaking and non-breaking
	const breaking = findings.filter((f) => f.isBreaking);
	const nonBreaking = findings.filter((f) => !f.isBreaking);

	if (breaking.length > 0) {
		lines.push(`## Breaking Changes`);
		lines.push(``);
		lines.push(`The following API changes require immediate attention:`);
		lines.push(``);
		for (const f of breaking) {
			lines.push(`### \`${f.apiName}\` — ${f.category}`);
			lines.push(``);
			lines.push(`- **File:** \`${f.file}\``);
			lines.push(`- **Line:** ${f.line}`);
			lines.push(`- **Code:** \`${f.lineContent}\``);
			lines.push(`- **Changelog:** ${f.description}`);
			lines.push(``);
		}
	}

	if (nonBreaking.length > 0) {
		lines.push(`## Simplifications & Non-Breaking Changes`);
		lines.push(``);
		lines.push(`The following changes may simplify or improve extension code:`);
		lines.push(``);
		for (const f of nonBreaking) {
			lines.push(`### \`${f.apiName}\` — ${f.category}`);
			lines.push(``);
			lines.push(`- **File:** \`${f.file}\``);
			lines.push(`- **Line:** ${f.line}`);
			lines.push(`- **Code:** \`${f.lineContent}\``);
			lines.push(`- **Changelog:** ${f.description}`);
			lines.push(``);
		}
	}

	// Migration hints
	lines.push(`## Suggested Actions`);
	lines.push(``);
	lines.push(`1. Review each finding in context`);
	lines.push(`2. Update affected API calls to match new patterns`);
	lines.push(`3. Test extension with updated APIs`);
	lines.push(`4. Close this issue when updates are complete`);
	lines.push(``);
	lines.push(`---`);
	lines.push(``);
	lines.push(`_Auto-generated by \`/check-extensions\` extension._`);

	return lines.join("\n");
}

/**
 * Check if gh CLI is authenticated.
 * Returns true if authenticated, false otherwise.
 */
export async function checkGhAuth(exec: ExecFn): Promise<boolean> {
	const result = await exec("gh", ["auth", "status"], { timeout: 10_000 });
	return result.code === 0;
}

/**
 * Ensure the extension-audit label exists on the repo.
 */
export async function ensureLabel(exec: ExecFn, repo: string): Promise<void> {
	// Check if label exists
	const listResult = await exec("gh", [
		"label",
		"list",
		"--repo",
		repo,
		"--search",
		"extension-audit",
	]);

	if (listResult.code === 0 && listResult.stdout.includes("extension-audit")) {
		return; // Label exists
	}

	// Create label
	const createResult = await exec("gh", [
		"label",
		"create",
		"extension-audit",
		"--repo",
		repo,
		"--description",
		"Extension audit tracking from /check-extensions",
		"--color",
		"A0D8F1",
	]);

	if (createResult.code !== 0) {
		throw new Error(
			`Failed to create label extension-audit: ${createResult.stderr || createResult.stdout}`,
		);
	}
}

/**
 * Check if an issue with the given title prefix already exists (open).
 * Returns true if a matching open issue exists.
 */
export async function checkExistingIssues(
	exec: ExecFn,
	repo: string,
	title: string,
): Promise<boolean> {
	// Extract prefix for search
	const prefix = title.split(":").slice(0, 2).join(":");

	const result = await exec("gh", [
		"issue",
		"list",
		"--repo",
		repo,
		"--label",
		"extension-audit",
		"--state",
		"open",
		"--search",
		prefix,
		"--json",
		"title,state,number",
	]);

	if (result.code !== 0) return false;

	try {
		const issues = JSON.parse(result.stdout);
		if (!Array.isArray(issues)) return false;

		// Check if any open issue has a matching title prefix
		return issues.some(
			(issue: { title?: string; state?: string }) =>
				issue.title?.startsWith(prefix) && issue.state === "OPEN",
		);
	} catch {
		return false;
	}
}

/**
 * Create a GitHub issue.
 * Returns the issue URL.
 */
export async function createIssue(
	exec: ExecFn,
	repo: string,
	title: string,
	body: string,
): Promise<string> {
	const result = await exec("gh", [
		"issue",
		"create",
		"--repo",
		repo,
		"--title",
		title,
		"--body",
		body,
		"--label",
		"extension-audit",
	]);

	if (result.code !== 0) {
		throw new Error(`Failed to create issue: ${result.stderr || result.stdout}`);
	}

	return result.stdout.trim();
}
